apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "savers-chart.fullname" . }}-pv
  namespace: {{ include "savers-chart.fullname" . }}-ns
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /mnt/minikube
    server: 10.0.2.15
