apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "savers-chart.fullname" . }}-pvc
  namespace: {{ include "savers-chart.fullname" . }}-ns
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: {{ include "savers-chart.fullname" . }}-pv
