apiVersion: v1
kind: Service
metadata:
  name: {{ include "savers-chart.fullname" . }}-svc
  namespace: {{ include "savers-chart.fullname" . }}-ns
  labels: 
    {{- include "savers-chart.labels" . | nindent 4 }}
spec:
  selector:
    app: savers-selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
